# Generated by Django 5.1 on 2026-02-08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='products/previews/', verbose_name='Превью')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Сколько продукта осталось')),
                ('quantity_unit', models.CharField(choices=[('L', 'Литры'), ('KG', 'Килограммы'), ('PCS', 'Штуки')], default='PCS', max_length=3, verbose_name='Единица измерения')),
                ('active_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Текущая скидка в процентах', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Действующая скидка')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Заархивирован')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductAdditionalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/additional/', verbose_name='Дополнительное фото')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='shopapp.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Дополнительное фото продукта',
                'verbose_name_plural': 'Дополнительные фото продуктов',
            },
        ),
    ]
